param(
    [ValidateSet('setup', 'start', 'stop', 'status')]
    [string]$Action = 'status',
    [string]$PostgresBin = $env:POSTGRES_BIN
)
$ErrorActionPreference = 'Stop'
$serverRoot = Split-Path -Parent $PSScriptRoot
$localRoot = Join-Path $serverRoot '.local'
$dataPath = Join-Path $localRoot 'postgres'
$envPath = Join-Path $serverRoot '.env.local'
$port = 5433

if (-not $PostgresBin) {
    $candidates = @('D:\postgrace\bin', "$env:ProgramFiles\PostgreSQL\18\bin", "$env:ProgramFiles\PostgreSQL\17\bin", "$env:ProgramFiles\PostgreSQL\16\bin")
    $command = Get-Command pg_ctl.exe -ErrorAction SilentlyContinue
    if ($command) { $candidates = @((Split-Path -Parent $command.Source)) + $candidates }
    $PostgresBin = $candidates | Where-Object { Test-Path -LiteralPath (Join-Path $_ 'initdb.exe') } | Select-Object -First 1
}
if (-not $PostgresBin) { throw 'PostgreSQL binaries were not found. Set POSTGRES_BIN to the PostgreSQL bin directory.' }
$pgCtl = Join-Path $PostgresBin 'pg_ctl.exe'
$initDb = Join-Path $PostgresBin 'initdb.exe'
$psql = Join-Path $PostgresBin 'psql.exe'
$createdb = Join-Path $PostgresBin 'createdb.exe'

function Invoke-PgCtl([string[]]$CommandArgs) {
    # PostgreSQL remains in the background after this hidden helper exits.
    $process = Start-Process -FilePath $pgCtl -ArgumentList $CommandArgs -WindowStyle Hidden -PassThru `
        -RedirectStandardOutput (Join-Path $localRoot 'pg-ctl.out.log') -RedirectStandardError (Join-Path $localRoot 'pg-ctl.err.log')
    # Cache the process handle before waiting so Windows retains its exit code.
    $processHandle = $process.Handle
    # Start-Process -Wait waits for descendants too, including the database daemon.
    $process.WaitForExit()
    if ($process.ExitCode -ne 0) {
        Get-Content -LiteralPath (Join-Path $localRoot 'pg-ctl.err.log')
        throw "pg_ctl failed with exit code $($process.ExitCode). See server/.local/postgres.log."
    }
}

if ($Action -eq 'setup') {
    New-Item -ItemType Directory -Force -Path $localRoot | Out-Null
    if (-not (Test-Path -LiteralPath (Join-Path $dataPath 'PG_VERSION'))) {
        if (Test-Path -LiteralPath $envPath) { throw '.env.local already exists. It has not been overwritten; use an existing local database or move that file before initializing a new cluster.' }
        $passwordBytes = New-Object byte[] 32
        $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
        $rng.GetBytes($passwordBytes)
        $rng.Dispose()
        $password = [BitConverter]::ToString($passwordBytes).Replace('-', '').ToLowerInvariant()
        $passwordFile = Join-Path $localRoot 'initdb-password.tmp'
        try {
            Set-Content -LiteralPath $passwordFile -Value $password -Encoding ascii
            & $initDb -D $dataPath -U healthu_dev --encoding=UTF8 --locale=C --auth=scram-sha-256 --pwfile=$passwordFile
            if ($LASTEXITCODE -ne 0) { throw 'PostgreSQL initialization failed.' }
            $localSettings = @(
                '# Local development only. Generated by scripts/local-postgres.ps1.'
                "DATABASE_URL=postgresql://healthu_dev:${password}@127.0.0.1:${port}/health_u_local?schema=public"
                'PORT=4000'
                'HOST=127.0.0.1'
                'CLIENT_URL=http://localhost:3000,http://127.0.0.1:3000,http://localhost:3100'
            )
            Set-Content -LiteralPath $envPath -Value $localSettings -Encoding ascii
        } finally {
            if (Test-Path -LiteralPath $passwordFile) { Remove-Item -LiteralPath $passwordFile }
        }
    }
}

if (-not (Test-Path -LiteralPath (Join-Path $dataPath 'PG_VERSION'))) { throw 'Run npm run db:local:setup first.' }
& $pgCtl status -D $dataPath
$running = $LASTEXITCODE -eq 0
if ($Action -eq 'status') { if (-not $running) { exit 3 }; exit 0 }
if ($Action -eq 'stop') {
    if ($running) { Invoke-PgCtl @('-D', "`"$dataPath`"", '-m', 'fast', '-w', 'stop') }
    exit 0
}
if (-not $running) {
    Invoke-PgCtl @('-D', "`"$dataPath`"", '-l', "`"$(Join-Path $localRoot 'postgres.log')`"", '-o', "`"-h 127.0.0.1 -p $port`"", '-w', 'start')
}

if ($Action -eq 'setup') {
    $databaseLine = Get-Content -LiteralPath $envPath | Where-Object { $_ -match '^DATABASE_URL=' } | Select-Object -First 1
    $databaseUrl = [Uri]($databaseLine -replace '^DATABASE_URL=', '')
    if ($databaseUrl.Host -ne '127.0.0.1' -or $databaseUrl.Port -ne $port -or $databaseUrl.AbsolutePath -ne '/health_u_local') {
        throw 'The local settings do not match this project cluster. No database was changed.'
    }
    $previousPassword = $env:PGPASSWORD
    try {
        $env:PGPASSWORD = [Uri]::UnescapeDataString(($databaseUrl.UserInfo -split ':', 2)[1])
        $exists = & $psql -h 127.0.0.1 -p $port -U healthu_dev -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname = 'health_u_local'"
        if ($LASTEXITCODE -ne 0) { throw 'Cannot connect to the local PostgreSQL cluster.' }
        if ($exists -ne '1') {
            & $createdb -h 127.0.0.1 -p $port -U healthu_dev health_u_local
            if ($LASTEXITCODE -ne 0) { throw 'Local database creation failed.' }
        }
    } finally { $env:PGPASSWORD = $previousPassword }
}
Write-Output "Local PostgreSQL ready at 127.0.0.1:$port (database: health_u_local)."
